import React from 'react';
import digitalmark from '../assets/banners/degitalmarkt.jpg';
import { FaCheckCircle } from 'react-icons/fa';

const Digitalmark = () => {
  return (
    <div className="container-fluid px-0">
      {/* Banner Image */}
      <div className="text-center mb-5">
        <img
          src={digitalmark}
          alt="One Time OTA Support"
          className="img-fluid"
          style={{ maxHeight: "100%" }}
        />
      </div>

      {/* Main Content */}
      <div className="container fs-5 py-5">
        <p>
          All marketing efforts for your hotel are aimed at generating revenue through room bookings.
          Our strategy revolves around creating content for Social Media – this is where most of your
          potential customers are. The content draws the customer to your website so he can take the
          next step of making his booking.
        </p>
        <p>
          The point is how to find the right kind of customer for your hotel. We use all the top
          industry-specific technologies and marketing strategies to find the right audience to
          showcase your hotel.
        </p>
        <p>
          These efforts include advertising on Social Media, Google, and OTAs by creating digital
          banners with links to your website. All the traffic generated by these banner promotions
          helps in your SEO ranking, but that alone may not be enough.
        </p>

        <h5 className="fw-bold mt-4">Our digital marketing efforts include:</h5>
        <ul className="list-unstyled">
          <li><FaCheckCircle className="text-success me-2" />SEO – Search Engine Optimization</li>
          <li><FaCheckCircle className="text-success me-2" />SEM – Search Engine Marketing</li>
          <li><FaCheckCircle className="text-success me-2" />Meta-Search Marketing</li>
          <li><FaCheckCircle className="text-success me-2" />Retargeting & Remarketing</li>
          <li><FaCheckCircle className="text-success me-2" />Reputation Management</li>
        </ul>

        <p className=" mt-3   mb-5" style={{ color: '#007F5F' }}>
          among other more complex methods of driving traffic to your website.
        </p>

        <p className="mt-4">
          The more ways people reach your website the better your overall ranking becomes, and
          ultimately more likely that they will select your hotel over a competitor’s.
       
          The important thing to note with all marketing efforts is that it should be consistent and
          spread over a long duration to have a long term benefit!
        </p>
      </div>
    </div>
  );
};

export default Digitalmark;
